language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test
  - cat "$(find coverage -name "*.info")" | ./node_modules/coveralls/bin/coveralls.js
