language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet
  - bower install --quiet
  - brunch build --production && brunch build --production
  - ./node_modules/coveralls/bin/coveralls.js

script:
  - karma start karma.coffee --browsers=Firefox --no-auto-watch --single-run
